name = "polychromatic"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Polychromatic"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a â†¦ b`
autoImplicit = false # no "assume a typo is a new variable"
relaxedAutoImplicit = false # no "assume a typo is a new variable"
linter.style.longLine = true # no lines longer than 100 chars
linter.style.multiGoal = true # no multiple active goals
linter.flexible = true # no rigid tactic (e.g. `exact`) after a flexible tactic (e.g. `simp`)

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "Polychromatic"

[[require]]
name = "subverso"
git = "https://github.com/leanprover/subverso"
rev = "no-modules/1d663ae67d8088111bb37c3c526fe2d43e4df01c"